In [1]:
from math import ceil, floor, modf

In [7]:
cellsize = 5
delta = cellsize / 2
delta1 = 0.1
tiny = 0.1
xmin = 659080
xmax = 688890
ymin = 4188820
ymax = 4208040

In [8]:
ncols = round((xmax - xmin)/cellsize) + 1
nrows = round((ymax - ymin)/cellsize) + 1
print(f'nrows = {nrows}, ncols = {ncols}')

nrows = 3845, ncols = 5963


In [50]:
x1 = xmax + 2 #xmin - 2 # 659078 , 4188822
y1 = ymax + 2 # 4208042 # ymin - 2 # 4188818
print(f'x1 = {x1}, y1 = {y1}')

if x1 >= xmax: #+ delta:
    x1 = xmax - tiny
if y1 >= ymax: #+ delta:
    y1 = ymax - tiny
if x1 <= xmin: #- delta:
    x1 = xmin # + tiny
if y1 <= ymin: #- delta:
    y1 = ymin # + tiny
    
xmin1 = xmin #- delta
xmax1 = xmax #+ delta
ymin1 = ymin #- delta
ymax1 = ymax #+ delta

xi = ((y1 - ymin) * nrows) / (ymax - ymin) 
xj = ((x1 - xmin) * ncols) / (xmax - xmin)
print(f'xi = {xi:f}, xj = {xj:f}')
print(f'i = {int(i):d}, j = {int(j):d}')
i = nrows - int(xi) - 1
j = int(xj)
print(f'i = {i:d}, j = {j:d}')

x1 = 688892, y1 = 4208042
xi = 3844.979995, xj = 5962.979997
i = 3844, j = 0
i = 0, j = 5962


In [5]:
# genero un tst general
p = ((xmin, ymin), (xmin, ymax), (xmax, ymax), (xmax, ymin))
delta = (2,-2, 2.5, 2.5, 2.6, -2.6)
points = []
for p1 in p:
    for d1 in delta:
        points.append([p1[0] + d1, p1[1] + d1])
points    

[[659082, 4188822],
 [659078, 4188818],
 [659082.5, 4188822.5],
 [659082.5, 4188822.5],
 [659082.6, 4188822.6],
 [659077.4, 4188817.4],
 [659082, 4208042],
 [659078, 4208038],
 [659082.5, 4208042.5],
 [659082.5, 4208042.5],
 [659082.6, 4208042.6],
 [659077.4, 4208037.4],
 [688892, 4208042],
 [688888, 4208038],
 [688892.5, 4208042.5],
 [688892.5, 4208042.5],
 [688892.6, 4208042.6],
 [688887.4, 4208037.4],
 [688892, 4188822],
 [688888, 4188818],
 [688892.5, 4188822.5],
 [688892.5, 4188822.5],
 [688892.6, 4188822.6],
 [688887.4, 4188817.4]]

In [5]:
# tests
import numpy as np

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a[:, [1, 2]]

array([[2, 3],
       [5, 6]])

In [77]:
x = 4.5
print(f'{x%1}, {ceil(x)}, {floor(x)}')

0.5, 5, 4


In [16]:
x0 = 659080; y0 = 4188820

In [29]:
delta = [(-2, -2), (-2, 2), (2, -2), (2, 2)]

In [30]:
xy = [[x0 + delta1[0], y0 + delta1[1]] for delta1 in delta]

In [3]:
import numpy as np

In [10]:
a = [i for i in range(9)]
a = np.array(a)
a = a.reshape((3,3))
print(a)
a[:, [1,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 2],
       [4, 5],
       [7, 8]])